# Generated by Django 4.1.3 on 2022-11-07 22:49

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_formdata_email_formdata_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='payment_register,', max_length=1000)),
                ('document', models.FileField(upload_to=form.models.user_upload_directory)),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Documents (Excel format)',
                'ordering': ('dateadded',),
            },
        ),
    ]
