# Generated by Django 4.1.3 on 2022-11-10 11:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_documentupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
