# Generated by Django 4.1.3 on 2022-11-10 12:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_documentupload_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='document'),
        ),
    ]
