# Generated by Django 4.1.3 on 2022-11-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_documentupload_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentUpload',
        ),
    ]
